swagger:
  title: Portal
  description: Poratl API Document
  version: 1.0.0
  name: genggao
  url:  http://geomodeling.njnu.edu.cn/
  email: wangminggis@163.com

spring:
  http:
    encoding:
      force: true
      charset: UTF-8
      enabled: true
  resources:
    static-locations: ["classpath:/META-INF/resources/", "classpath:/resources/", "classpath:/static/", "classpath:/public/","file:${prop.upload-folder}"]
  data:
    mongodb:
      #uri: mongodb://222.192.7.75:27017/Task
      authentication-database: Task
      database: Task
      host: 222.192.7.75
      port: 23266
      username: task
      password: task123
  profiles:
    active: dev
  cache:
    type: simple
  servlet:
    multipart:
      max-file-size: 1000MB
      max-request-size: 1000MB
#      location: /home/portal/ManagerServer/DemoData/
      location: F:/managerServer/Temp
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    encoding: UTF-8
    cache: false
    check-template-location: true
  mvc:
    static-path-pattern: /**

prop:
#  upload-folder: /home/portal/ManagerServer/DemoData/
#  package-folder: /home/portal/ManagerServer/geo_model/
#  task-upload: /home/portal/ManagerServer/task/
  upload-folder: F:/summer2/a/upload
  package-folder: F:/summer2/a/geo_model
  task-upload: F:/summer2/a/task
  managerServerIpAndPort: 127.0.0.1:8084


