server:
  port: 8084
  servlet:
    context-path: /GeoModeling
  compression:
    enabled: true
    mime-types:
      - application/json
      - application/xml
      - text/html
      - text/xml
      - text/plain
    min-response-size: 1024

spring:
  servlet:
    multipart:
      max-file-size: 1000MB
      max-request-size: 1000MB
      location: /home/portal/ManagerServer/DemoData/